### ISSUE TITLE
spdlog 1.12 externalizes fmt and this may break WCT build

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-spack#12]
Corey Adams discovered a possible problem building WCT against SPDLOG 1.12 via Spack while I have things built with 1.11.  In 1.12, SPDLOG allows `fmt` to be provided externally and this may be the origin of the problem.

Try out a build with 1.12 and fix whatever may be broken or confirm it works with these Spack package.py's.

**Comment by brettviren** [comment]
The core issue seems to be that fmtlib is no longer so simple as to just require `operator<<`.  https://fmt.dev/latest/api.html#ostream-api

We must now supply a `fmt::formatter<T>`.

But, this must NOT be supplied when building against an older fmtlib.  It looks like this came to be in v9 of fmtlib.

```
Disabled automatic std::ostream insertion operator (operator<<) discovery 
when fmt/ostream.h is included to prevent ODR violations. You can get the 
old behavior by defining FMT_DEPRECATED_OSTREAM but this will be removed 
in the next major release. Use fmt::streamed or fmt::ostream_formatter to
enable formatting via std::ostream instead.
```

**Comment by brettviren** [comment]
Annoying.  spdlog includes fmtlib with some loose spdlog+fmtlib version correspondence and also spdlog can take build-time direction to use external fmtlib.  Then, fmtlib API changes at least once somewhere in its history.  Then, to make this all more horrible, I don't know what combos are in the wild and in any case can only test easily with up-to-date versions.

So, I bite the bullet and make some combinations with Spack and a stand-alone test.

SPDLOG 1.8.0 release note says `Upgraded bundled fmt to version 7.0.3.`.

Nearest fmtlib that Spack has is `7.1.{0,2,3}`.

```
$ spack install spdlog@1.8.2+shared ^fmt@7.1.3
$ emacs test-spdlog.cpp
$ spack view add -i spdlog-1.8.2/local spdlog@1.8.2
$ echo 'load_prefix local' > spdlog-1.8.2/.envrc
$ cd spdlog-1.8.2/
$ direnv allow
$ pkg-config spdlog --cflags --libs
-I/srv/spack/local/opt/spack/linux-debian12-haswell/gcc-12.2.0/spdlog-1.8.2-n6hb5fzv44rcvebwubzlk4pbw37efrqe/include -DSPDLOG_SHARED_LIB -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/srv/spack/local/opt/spack/linux-debian12-haswell/gcc-12.2.0/fmt-7.1.3-4stbnsz7dadgo3afcvsrs6ufp7zuro6r/include -L/srv/spack/local/opt/spack/linux-debian12-haswell/gcc-12.2.0/spdlog-1.8.2-n6hb5fzv44rcvebwubzlk4pbw37efrqe/lib -lspdlog -pthread -L/srv/spack/local/opt/spack/linux-debian12-haswell/gcc-12.2.0/fmt-7.1.3-4stbnsz7dadgo3afcvsrs6ufp7zuro6r/lib -lfmt

$ g++ -Wall -std=c++17 -o test-spdlog-fmtlib ../test-spdlog-fmtlib.cpp (pkg-config spdlog --cflags --libs | string split ' ') 
```

Also

```
spack install spdlog@1.11.0+shared ^fmt@9.1.0
spack install spdlog@1.10.0+shared ^fmt@8.1.1
spack install spdlog@1.9.2+shared ^fmt@8.1.1
spack install spdlog@1.13.0+shared
```

For each `<version>` of spdlog:

```
   spack view add -i spdlog-<version>/local spdlog@<version>
   echo 'load_prefix local' > spdlog-<version>/.envrc
   cd spdlog-<version>/
   direnv allow

   g++ -Wall -std=c++17 \
        -o test-spdlog-fmtlib \
        ../test-spdlog-fmtlib.cpp \
        (pkg-config spdlog --cflags --libs | string split ' ')    

        (fish syntax)

   ./test-spdlog-fmtlib 
```

The `test-spdlog-fmtlib.cpp` is in WCT's `util/test/`.

**Comment by brettviren** [comment]
@HaiwangYu a little more work is needed before closing this.  As-is, it will still build old WCT against new spdlog/fmtlib. 

Can you please make a new WCT release 0.28.0?  I'll then add Spack bits so to force older spdlog/fmtlib for prior releases.

**Comment by HaiwangYu** [comment]
@brettviren just tagged a 0.28.0 release.

**Comment by brettviren** [comment]
Thanks, @HaiwangYu 

There's now a corresponding release for wire-cell-spack:

https://github.com/WireCell/wire-cell-spack/releases/tag/0.28.0.0

and now I think this issue is done.
